#!/usr/bin/env python3
"""Vendor every registry entry at its pinned commit and regenerate the marketplace.
Stdlib only. Usage: python tools/sync.py"""
import io, json, pathlib, re, shutil, sys, tarfile, urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
PLUG = ROOT / "plugins"
LICENSE_NAMES = ("LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING", "NOTICE")

def put(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.encode("utf-8"))

def fetch(repo, sha):
    url = f"https://codeload.github.com/{repo}/tar.gz/{sha}"
    req = urllib.request.Request(url, headers={"User-Agent": "ai4science-skills-sync"})
    with urllib.request.urlopen(req, timeout=180) as r:
        data = r.read()
    return tarfile.open(fileobj=io.BytesIO(data), mode="r:gz")

def vendor(e):
    name = e["name"]
    if not re.fullmatch(r"[a-f0-9]{40}", e.get("sha", "")):
        sys.exit(f"{name}: sha must be a full 40-character commit id")
    dest = PLUG / name
    if dest.exists():
        shutil.rmtree(dest)
    base = e.get("path", "skills").strip("/")
    wanted = set(e.get("skills") or [])
    found = set()
    tf = fetch(e["repo"], e["sha"])
    for m in tf.getmembers():
        if not m.isfile():
            continue
        parts = m.name.split("/", 1)
        if len(parts) < 2 or ".." in pathlib.PurePosixPath(parts[1]).parts:
            continue
        rel = parts[1]
        if rel in LICENSE_NAMES:
            target = dest / rel
        elif rel.startswith(base + "/"):
            sub = rel[len(base) + 1:]
            skill = sub.split("/", 1)[0]
            if wanted and skill not in wanted:
                continue
            found.add(skill)
            target = dest / "skills" / sub
        else:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(tf.extractfile(m).read())
    if wanted - found:
        sys.exit(f"{name}: skills not found at pinned commit: {sorted(wanted - found)}")
    skills = sorted(s for s in found if (dest / "skills" / s / "SKILL.md").exists())
    if not skills:
        sys.exit(f"{name}: no SKILL.md found under {base}/ at pinned commit")
    put(dest / "SOURCE.json", json.dumps({"repo": e["repo"], "ref": e.get("ref"), "sha": e["sha"], "path": base}, indent=2) + "\n")
    return skills

def main():
    reg = json.loads((ROOT / "registry.json").read_text("utf-8"))
    PLUG.mkdir(exist_ok=True)
    plugins, rows, keep = [], [], set()
    for e in reg["plugins"]:
        skills = vendor(e)
        keep.add(e["name"])
        plugins.append({
            "name": e["name"],
            "description": e["description"],
            "source": f"./plugins/{e['name']}",
            "strict": False,
            "skills": [f"./skills/{s}" for s in skills],
            "author": {"name": e["maintainer"]},
            "license": e["license"],
            "homepage": f"https://github.com/{e['repo']}/tree/{e['sha']}",
        })
        hosted = "; ".join(e.get("hosted_services") or []) or "none"
        rows.append(f"| {e['name']} | {', '.join(skills)} | {e['maintainer']} | {e['license']} | [{e['repo']}@{e['sha'][:12]}](https://github.com/{e['repo']}/tree/{e['sha']}) | {hosted} |")
        print(f"vendored {e['name']}: {', '.join(skills)}")
    for d in PLUG.iterdir():
        if d.is_dir() and d.name not in keep:
            shutil.rmtree(d)
    market = {"name": reg["name"], "owner": reg["owner"],
              "metadata": {"description": reg["description"], "version": reg["version"]},
              "plugins": plugins}
    put(ROOT / ".claude-plugin" / "marketplace.json", json.dumps(market, indent=2) + "\n")
    put(ROOT / "CATALOG.md", "# Catalog\n\nGenerated by tools/sync.py from registry.json. Do not edit by hand.\n\n"
        "| Plugin | Skills | Maintainer | License | Pinned source | External services |\n|---|---|---|---|---|---|\n"
        + "\n".join(rows) + "\n")
    print(f"synced {len(plugins)} plugin(s)")

if __name__ == "__main__":
    main()